// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBrt6Su5tNZGYsY7uou2SLvEvTQFRYI98',
    appId: '1:180382469215:web:c83d91d563d75d4f709fea',
    messagingSenderId: '180382469215',
    projectId: 'keys-45615',
    authDomain: 'keys-45615.firebaseapp.com',
    storageBucket: 'keys-45615.appspot.com',
    measurementId: 'G-QJ8E070257',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhf9YvZo7ufA2-r-Z92bgTIG40vF5eGaI',
    appId: '1:180382469215:android:1522624c597aa338709fea',
    messagingSenderId: '180382469215',
    projectId: 'keys-45615',
    storageBucket: 'keys-45615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcWNCUjmB40HyAzXP-aGmhXXJZrKdRRvY',
    appId: '1:180382469215:ios:c76ac8921efa4cd7709fea',
    messagingSenderId: '180382469215',
    projectId: 'keys-45615',
    storageBucket: 'keys-45615.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcWNCUjmB40HyAzXP-aGmhXXJZrKdRRvY',
    appId: '1:180382469215:ios:c76ac8921efa4cd7709fea',
    messagingSenderId: '180382469215',
    projectId: 'keys-45615',
    storageBucket: 'keys-45615.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBrt6Su5tNZGYsY7uou2SLvEvTQFRYI98',
    appId: '1:180382469215:web:78ef7de7093ff531709fea',
    messagingSenderId: '180382469215',
    projectId: 'keys-45615',
    authDomain: 'keys-45615.firebaseapp.com',
    storageBucket: 'keys-45615.appspot.com',
    measurementId: 'G-NW9ZM9H1EW',
  );
}
